# Generated by Django 4.2.26 on 2025-12-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0003_schedule_entities'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='availabilityslot',
            new_name='rota_availa_user_id_01b9ab_idx',
            old_name='rota_avail_user_st_90c39d_idx',
        ),
    ]
