# Generated by Django 6.0 on 2025-12-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('team_member', 'Team Member'), ('rota_manager', 'Rota Manager'), ('service_manager', 'Service Manager'), ('system_admin', 'System Admin')], default='team_member', max_length=20),
        ),
    ]
