# Generated by Django 6.0 on 2025-12-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_end_time',
            field=models.TimeField(blank=True, help_text='e.g. 17:00', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='default_start_time',
            field=models.TimeField(blank=True, help_text='e.g. 09:00', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.CharField(blank=True, choices=[('Alpha', 'Team Alpha'), ('Bravo', 'Team Bravo'), ('Charlie', 'Team Charlie'), ('Delta', 'Team Delta')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='Europe/London', max_length=50),
        ),
    ]
